"""
FLUX v4 Deployment Compilation Pipeline.

Compiles GUARD constraint definitions to different deployment targets:
  - C (with AVX2 SIMD, auto-compiles with gcc -O3 -mavx2)
  - WASM (hand-written WAT, zero imports, pure computation)
  - Verilog (synthesizable, single-clock-cycle, pipelined)
  - ARM Cortex-M4 assembly (Thumb-2, hard-float)

Usage:
    from flux_deploy import deploy, compile_to_c, compile_to_wasm, ...
    from flux_constraint_exact import PRESETS

    deploy("c", PRESETS["automotive_can"], "build/automotive_c")
    deploy("all", PRESETS["automotive_can"], "build/automotive_all")
"""

from __future__ import annotations

import math
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

Constraint = Dict[str, Any]  # {"lo": float, "hi": float, "name": str}
Constraints = Sequence[Constraint]

# Severity table (matches C header / spec)
_SEVERITY_TABLE = [0, 1, 1, 2, 2, 3, 3, 3, 3]  # index = popcount(error_mask)

_SEVERITY_NAMES = ["PASS", "CAUTION", "WARNING", "CRITICAL"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _c_float(v: float) -> str:
    """Format a Python float as a C float literal."""
    if math.isinf(v):
        return "INFINITY" if v > 0 else "(-INFINITY)"
    if math.isnan(v):
        return "NAN"
    s = repr(v)
    # Ensure it looks like a float (has a dot or 'e')
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0f"
    elif not s.endswith("f"):
        s += "f"
    return s


def _c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _sanitize_identifier(s: str) -> str:
    """Make a string safe for use as a C/Verilog identifier."""
    out = []
    for ch in s:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    return "".join(out) if out else "c0"


def _verilog_real(v: float) -> str:
    """Format a Python float for Verilog real literal."""
    if math.isinf(v):
        return "1.0/0.0" if v > 0 else "-1.0/0.0"
    return repr(v)


# ---------------------------------------------------------------------------
# 1. compile_to_c
# ---------------------------------------------------------------------------

def compile_to_c(constraints: Constraints, output_path: Union[str, Path]) -> Path:
    """
    Generate a standalone C file with:
    - Constraint bounds as static arrays
    - flux_check_exact() hot path inlined
    - main() with benchmark harness
    - Compiles with gcc -O3 -mavx2 automatically
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    n = len(constraints)
    names = [c.get("name", f"C{i}") for i, c in enumerate(constraints)]
    lo_vals = [float(c["lo"]) for c in constraints]
    hi_vals = [float(c["hi"]) for c in constraints]

    lines: List[str] = []
    a = lines.append

    # ── Header ──────────────────────────────────────────────
    a("/*")
    a(" * FLUX Exact Constraint Engine — Auto-generated C Deployment")
    a(f" * Constraints: {n}")
    for i, nm in enumerate(names):
        a(f" *   [{i}] {nm}: [{lo_vals[i]}, {hi_vals[i]}]")
    a(" * Generated by flux_deploy.compile_to_c()")
    a(" */")
    a("")
    a("#include <stdio.h>")
    a("#include <stdlib.h>")
    a("#include <string.h>")
    a("#include <math.h>")
    a("#include <stdint.h>")
    a("#include <stdbool.h>")
    a("#include <time.h>")
    a("")
    a(f"#define N_CONSTRAINTS {n}")
    a(f"#define FLUX_EXACT_MAX_CONSTRAINTS 8")
    a("")

    # ── Bounds arrays ───────────────────────────────────────
    a("/* Constraint bounds */")
    lo_strs = ", ".join(_c_float(v) for v in lo_vals)
    hi_strs = ", ".join(_c_float(v) for v in hi_vals)
    a(f"static const float BOUNDS_LO[FLUX_EXACT_MAX_CONSTRAINTS] = {{{lo_strs}}};")
    a(f"static const float BOUNDS_HI[FLUX_EXACT_MAX_CONSTRAINTS] = {{{hi_strs}}};")
    a("")
    a("static const char* const CONSTRAINT_NAMES[FLUX_EXACT_MAX_CONSTRAINTS] = {")
    for nm in names:
        a(f'    "{_c_escape(nm)}",')
    a("};")
    a("")

    # ── Severity table ──────────────────────────────────────
    a("static const uint8_t SEVERITY_TABLE[9] = {0, 1, 1, 2, 2, 3, 3, 3, 3};")
    a("")

    # ── Hot path: flux_check_exact ──────────────────────────
    a("/* ── Hot path: returns error_mask (0 = pass) ──────── */")
    a("")
    a("static inline uint8_t flux_check_exact(float val) {")
    a("    if (val != val) return (1u << N_CONSTRAINTS) - 1u;  /* NaN violates all */")
    a("    uint8_t mask = 0;")
    for i in range(n):
        a(f"    if (val < BOUNDS_LO[{i}] || val > BOUNDS_HI[{i}])")
        a(f"        mask |= (1u << {i});")
    a("    return mask;")
    a("}")
    a("")

    # ── Batch check (scalar) ────────────────────────────────
    a("static void flux_check_batch(const float* values, int count, uint8_t* masks) {")
    a("    for (int i = 0; i < count; i++) {")
    a("        masks[i] = flux_check_exact(values[i]);")
    a("    }")
    a("}")
    a("")

    # ── Severity helper ─────────────────────────────────────
    a("static const char* severity_name(uint8_t mask) {")
    a("    uint8_t count = 0; uint8_t m = mask;")
    a("    while (m) { count++; m &= m - 1; }")
    a("    switch (SEVERITY_TABLE[count > 8 ? 8 : count]) {")
    a("        case 0: return \"PASS\";")
    a("        case 1: return \"CAUTION\";")
    a("        case 2: return \"WARNING\";")
    a("        case 3: return \"CRITICAL\";")
    a("        default: return \"UNKNOWN\";")
    a("    }")
    a("}")
    a("")

    # ── Print result helper ─────────────────────────────────
    a("static void print_result(float val, uint8_t mask) {")
    a('    printf("  val=%.4f  mask=0x%02x  severity=%s", val, mask, severity_name(mask));')
    a("    if (mask) {")
    a('        printf("  violated:");')
    for i in range(n):
        a(f'        if (mask & (1u << {i})) printf(" {names[i]}");')
    a("    }")
    a('    printf("\\n");')
    a("}")
    a("")

    # ── Timing helper ───────────────────────────────────────
    a("static double now_sec(void) {")
    a("    struct timespec ts;")
    a("    clock_gettime(CLOCK_MONOTONIC, &ts);")
    a("    return ts.tv_sec + ts.tv_nsec * 1e-9;")
    a("}")
    a("")

    # ── Main: correctness + benchmark ───────────────────────
    a("int main(void) {")
    a(f'    printf("=== FLUX Exact Check — Auto-generated ({n} constraints) ===\\n\\n");')
    a("")
    a("    /* Correctness tests */")
    a('    printf("Correctness tests:\\n");')
    a("    int pass = 0, fail = 0;")
    a("")

    # Pre-compute expected error_masks for test values in Python
    # This is critical because a value at constraint i's boundary may
    # violate other constraints (e.g., -40 passes coolant but fails engine_rpm).
    def _expected_mask(val):
        if math.isnan(val):
            return (1 << n) - 1
        mask = 0
        for j in range(n):
            if val < lo_vals[j] or val > hi_vals[j]:
                mask |= (1 << j)
        return mask

    a("    /* Correctness tests with pre-computed expected masks */")
    a("")

    # Test each constraint boundary
    test_cases = []
    for i in range(n):
        lo_c = _c_float(lo_vals[i])
        hi_c = _c_float(hi_vals[i])
        # lo boundary
        test_cases.append((f"{names[i]} lo={lo_c}", lo_vals[i], _expected_mask(lo_vals[i])))
        # hi boundary
        test_cases.append((f"{names[i]} hi={hi_c}", hi_vals[i], _expected_mask(hi_vals[i])))
        # Just outside
        if lo_vals[i] != hi_vals[i]:
            below = lo_vals[i] - 0.001
            above = hi_vals[i] + 0.001
            test_cases.append((f"{names[i]} below lo", below, _expected_mask(below)))
            test_cases.append((f"{names[i]} above hi", above, _expected_mask(above)))

    # NaN test
    test_cases.append(("NaN", float('nan'), (1 << n) - 1))

    for desc, val, expected in test_cases:
        if math.isnan(val):
            val_c = "NAN"
        else:
            val_c = _c_float(val)
        a(f'    {{ uint8_t got = flux_check_exact({val_c});')
        a(f'      uint8_t exp = 0x{expected:02x};')
        a(f'      if (got == exp) pass++;')
        a(f'      else {{ fail++; printf("  FAIL: {desc} got=0x%02x exp=0x%02x\\n", got, exp); }}')
        a(f'    }}')

    a("")
    a("")
    a('    printf("  Passed: %d / %d\\n\\n", pass, pass + fail);')
    a("")
    a("    /* Benchmark */")
    a("    const int ITERS = 10000000;")
    a("    float* vals = malloc(ITERS * sizeof(float));")
    a("    uint8_t* masks_out = malloc(ITERS);")
    a("    for (int i = 0; i < ITERS; i++) vals[i] = (float)((i % 1000) - 500);")
    a("")
    a("    double t0 = now_sec();")
    a("    flux_check_batch(vals, ITERS, masks_out);")
    a("    double elapsed = now_sec() - t0;")
    a("    double rate = ITERS / elapsed;")
    a('    printf("Benchmark (%d constraints, %d iters):\\n", N_CONSTRAINTS, ITERS);')
    a('    printf("  Scalar: %.1fM checks/sec (%.3fms)\\n", rate / 1e6, elapsed * 1000);')
    a("")
    a("    free(vals);")
    a("    free(masks_out);")
    a("")
    a("    return fail > 0 ? 1 : 0;")
    a("}")
    a("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


# ---------------------------------------------------------------------------
# 2. compile_to_wasm
# ---------------------------------------------------------------------------

def compile_to_wasm(constraints: Constraints, output_path: Union[str, Path]) -> Path:
    """
    Generate a WASM module (WAT format):
    - Export check(f64) -> i32: check single value, return error_mask
    - Export check_batch(ptr, len) -> void: batch check into memory
    - Zero imports — pure computation
    - Uses wat2wasm if available, otherwise outputs WAT
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    n = len(constraints)
    lo_vals = [float(c["lo"]) for c in constraints]
    hi_vals = [float(c["hi"]) for c in constraints]

    lines: List[str] = []
    a = lines.append

    a(";; FLUX Exact Constraint Engine — Auto-generated WASM Deployment")
    a(f";; Constraints: {n}")
    a(";; Zero imports. Pure computation. Deterministic.")
    a(";;")
    a(";; Exports:")
    a(";;   check(f64) -> i32       — single value check, returns error_mask")
    a(";;   check_batch(i32, i32)   — batch check (ptr, len), writes masks to memory")
    a(";;   memory                  — 1 page (64KB)")
    a("")
    a("(module")

    # Memory: 1 page for batch results
    a('  (memory (export "memory") 1 1)')
    a("")

    # Constraint bounds as globals
    for i in range(n):
        a(f"  (global $lo_{i} f64 (f64.const {repr(lo_vals[i])}))")
        a(f"  (global $hi_{i} f64 (f64.const {repr(hi_vals[i])}))")
    a("")

    # ── check(f64) -> i32 ───────────────────────────────────
    a('  (func (export "check") (param $val f64) (result i32)')
    a("    (local $mask i32)")
    a("    (local.set $mask (i32.const 0))")
    a("")
    a("    ;; NaN check: val != val")
    a("    (if (f64.ne (local.get $val) (local.get $val))")
    a("      (then (return (i32.const {}))".format((1 << n) - 1))
    a("    )")
    a("")

    # Per-constraint check
    for i in range(n):
        a(f"    ;; Constraint {i}: [{lo_vals[i]}, {hi_vals[i]}]")
        a(f"    (if (i32.or")
        a(f"          (f64.lt (local.get $val) (global.get $lo_{i}))")
        a(f"          (f64.gt (local.get $val) (global.get $hi_{i}))")
        a(f"        )")
        a(f"      (then")
        a(f"        (local.set $mask (i32.or (local.get $mask) (i32.const {1 << i})))")
        a(f"      )")
        a(f"    )")
        a("")

    a("    (local.get $mask)")
    a("  )")
    a("")

    # ── check_batch(ptr, len) ────────────────────────────────
    a('  (func (export "check_batch") (param $ptr i32) (param $len i32)')
    a("    (local $i i32)")
    a("    (local $val f64)")
    a("    (local $mask i32)")
    a("")
    a("    (local.set $i (i32.const 0))")
    a("    (block $done")
    a("      (loop $loop")
    a("        (br_if $done (i32.ge_u (local.get $i) (local.get $len)))")
    a("")
    a("        ;; Load f64 value from input array")
    a("        ;; Input values start at offset 0x1000")
    a("        (local.set $val (f64.load (i32.add (i32.const 0x1000)")
    a("          (i32.mul (local.get $i) (i32.const 8)))))")
    a("")
    a("        ;; NaN check")
    a("        (if (f64.ne (local.get $val) (local.get $val))")
    a("          (then")
    a("            (local.set $mask (i32.const {}))".format((1 << n) - 1))
    a("          )")
    a("          (else")
    a("            (local.set $mask (i32.const 0))")
    for i in range(n):
        a(f"            (if (i32.or")
        a(f"                  (f64.lt (local.get $val) (global.get $lo_{i}))")
        a(f"                  (f64.gt (local.get $val) (global.get $hi_{i}))")
        a(f"                )")
        a(f"              (then")
        a(f"                (local.set $mask (i32.or (local.get $mask) (i32.const {1 << i})))")
        a(f"              )")
        a(f"            )")
    a("          )")
    a("        )")
    a("")
    a("        ;; Store result mask at output offset")
    a("        ;; Output masks start at offset 0x4000")
    a("        (i32.store8 (i32.add (i32.const 0x4000) (local.get $i))")
    a("          (local.get $mask))")
    a("")
    a("        (local.set $i (i32.add (local.get $i) (i32.const 1)))")
    a("        (br $loop)")
    a("      )")
    a("    )")
    a("  )")
    a("")
    a("  ;; End of module")
    a(")")

    wat_path = output_path if output_path.suffix == ".wat" else output_path.with_suffix(".wat")
    wat_path.write_text("\n".join(lines), encoding="utf-8")

    # Try to compile with wat2wasm
    wasm_path = wat_path.with_suffix(".wasm")
    try:
        result = subprocess.run(
            ["wat2wasm", str(wat_path), "-o", str(wasm_path)],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return wasm_path
    except FileNotFoundError:
        pass

    # Return WAT if wat2wasm not available
    return wat_path


# ---------------------------------------------------------------------------
# 3. compile_to_verilog
# ---------------------------------------------------------------------------

def compile_to_verilog(constraints: Constraints, output_path: Union[str, Path]) -> Path:
    """
    Generate synthesizable Verilog:
    - Each constraint becomes a comparator
    - Output is an 8-bit error_mask
    - Single clock cycle latency
    - Pipelined for batch throughput
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    n = len(constraints)
    names = [c.get("name", f"C{i}") for i, c in enumerate(constraints)]
    lo_vals = [float(c["lo"]) for c in constraints]
    hi_vals = [float(c["hi"]) for c in constraints]

    lines: List[str] = []
    a = lines.append

    a("/// ------------------------------------------------------------------")
    a("/// FLUX Exact Constraint Engine — Auto-generated Verilog")
    a(f"/// Constraints: {n}")
    a("/// Single clock cycle latency, pipelined for batch throughput")
    a("/// ------------------------------------------------------------------")
    a("")
    a("module flux_checker (")
    a("    input  wire        clk,")
    a("    input  wire        rst_n,")
    a("    input  wire        valid_in,")
    a("    input  wire [63:0] value_in,    // IEEE 754 double")
    a("    output reg  [7:0]  error_mask,")
    a("    output reg         valid_out")
    a(");")
    a("")

    # ── Internal signals ────────────────────────────────────
    a("    wire [63:0] val;")
    a("    reg  stage_valid;")
    a("")
    a("    // Pipeline register")
    a("    always @(posedge clk or negedge rst_n) begin")
    a("        if (!rst_n) begin")
    a("            val         <= 64'd0;")
    a("            stage_valid <= 1'b0;")
    a("        end else begin")
    a("            val         <= value_in;")
    a("            stage_valid <= valid_in;")
    a("        end")
    a("    end")
    a("")

    # ── Constraint comparators ──────────────────────────────
    a("    // Constraint comparators (combinational)")
    a("    wire [7:0] violations;")
    for i in range(n):
        ident = _sanitize_identifier(names[i])
        lo_v = _verilog_real(lo_vals[i])
        hi_v = _verilog_real(hi_vals[i])
        a(f"    wire viol_{ident};")
        a(f"    // {names[i]}: [{lo_vals[i]}, {hi_vals[i]}]")
        a(f"    assign viol_{ident} = ($bitstoreal(val) < {lo_v}) || ($bitstoreal(val) > {hi_v});")
    a("")

    # ── NaN detection ───────────────────────────────────────
    a("    // NaN detection: exponent all 1s, mantissa non-zero")
    a("    wire is_nan;")
    a("    assign is_nan = (val[62:52] == 11'b11111111111) && (val[51:0] != 52'd0);")
    a("")

    # ── Assemble error_mask ─────────────────────────────────
    a("    // Assemble error_mask from violations")
    a("    always @(posedge clk or negedge rst_n) begin")
    a("        if (!rst_n) begin")
    a("            error_mask <= 8'd0;")
    a("            valid_out  <= 1'b0;")
    a("        end else if (stage_valid) begin")
    if n > 0:
        idents = [_sanitize_identifier(names[i]) for i in range(n)]
        mask_bits = " }".join(f", viol_{idents[i]}" for i in range(n))
        remaining = ", 1'b0" * (8 - n) if n < 8 else ""
        a(f"            error_mask <= is_nan ? 8'b{_int_to_bin((1 << n) - 1, 8)} : {{ {mask_bits}{remaining} }};")
    else:
        a("            error_mask <= 8'd0;")
    a("            valid_out  <= 1'b1;")
    a("        end else begin")
    a("            valid_out  <= 1'b0;")
    a("        end")
    a("    end")
    a("")
    a("endmodule")
    a("")

    # ── Testbench ───────────────────────────────────────────
    a("/// ------------------------------------------------------------------")
    a("/// Testbench")
    a("/// ------------------------------------------------------------------")
    a("")
    a("module flux_checker_tb;")
    a("    reg         clk;")
    a("    reg         rst_n;")
    a("    reg         valid_in;")
    a("    reg  [63:0] value_in;")
    a("    wire [7:0]  error_mask;")
    a("    wire        valid_out;")
    a("")
    a("    flux_checker uut (")
    a("        .clk(clk),")
    a("        .rst_n(rst_n),")
    a("        .valid_in(valid_in),")
    a("        .value_in(value_in),")
    a("        .error_mask(error_mask),")
    a("        .valid_out(valid_out)")
    a("    );")
    a("")
    a("    always #5 clk = ~clk;")
    a("")
    a("    initial begin")
    a("        $display(\"=== FLUX Verilog Testbench ===\");")
    a("        clk = 0; rst_n = 0; valid_in = 0; value_in = 0;")
    a("        #10 rst_n = 1;")
    a("")
    # Test each constraint boundary
    for i in range(n):
        ident = _sanitize_identifier(names[i])
        a(f"        // Test {names[i]}")
        a(f"        valid_in = 1; value_in = $realtobits({lo_vals[i]}); #10;")
        a(f"        if (valid_out && error_mask[{i}] !== 1'b0) $display(\"FAIL: {names[i]} lo should pass\");")
        a(f"        valid_in = 1; value_in = $realtobits({hi_vals[i]}); #10;")
        a(f"        if (valid_out && error_mask[{i}] !== 1'b0) $display(\"FAIL: {names[i]} hi should pass\");")
        a(f"        valid_in = 1; value_in = $realtobits({lo_vals[i]} - 0.001); #10;")
        a(f"        if (valid_out && error_mask[{i}] !== 1'b1) $display(\"FAIL: {names[i]} below lo should violate\");")
        a(f"        valid_in = 1; value_in = $realtobits({hi_vals[i]} + 0.001); #10;")
        a(f"        if (valid_out && error_mask[{i}] !== 1'b1) $display(\"FAIL: {names[i]} above hi should violate\");")
        a("")
    a("        valid_in = 0;")
    a('        $display("All tests completed.");')
    a("        $finish;")
    a("    end")
    a("endmodule")

    v_path = output_path if output_path.suffix == ".v" else output_path.with_suffix(".v")
    v_path.write_text("\n".join(lines), encoding="utf-8")
    return v_path


def _int_to_bin(val: int, width: int) -> str:
    """Format integer as binary literal with given width."""
    return format(val & ((1 << width) - 1), f'0{width}b')


# ---------------------------------------------------------------------------
# 4. compile_to_asm_arm
# ---------------------------------------------------------------------------

def compile_to_asm_arm(constraints: Constraints, output_path: Union[str, Path]) -> Path:
    """
    Generate ARM Cortex-M4 assembly:
    - Thumb-2 instructions
    - Hard-float comparisons (FPU)
    - Inlined constraint loop
    - Returns error_mask in r0
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    n = len(constraints)
    names = [c.get("name", f"C{i}") for i, c in enumerate(constraints)]
    lo_vals = [float(c["lo"]) for c in constraints]
    hi_vals = [float(c["hi"]) for c in constraints]

    lines: List[str] = []
    a = lines.append

    a("    .syntax unified")
    a("    .cpu cortex-m4")
    a("    .fpu fpv4-sp-d16")
    a("    .thumb")
    a("")
    a("    .section .rodata")
    a("    .align 2")
    a("")

    # ── Constants pool ──────────────────────────────────────
    a("bounds_lo:")
    for v in lo_vals:
        a(f"    .float {_arm_float(v)}")
    a("")
    a("bounds_hi:")
    for v in hi_vals:
        a(f"    .float {_arm_float(v)}")
    a("")
    a("constraint_names:")
    for nm in names:
        a(f'    .asciz "{_c_escape(nm)}"')
        a("    .align 1")
    a("")

    # ── Text section ────────────────────────────────────────
    a("    .section .text")
    a("    .align 2")
    a("    .global flux_check_exact")
    a("    .thumb_func")
    a("")
    a("    /// flux_check_exact(float val) -> uint8_t error_mask")
    a("    /// Input: s0 = value to check")
    a("    /// Output: r0 = error_mask (0 = all pass)")
    a("    /// Clobbers: r1, r2, s1, s2, s3")
    a("flux_check_exact:")
    a("    push    {r4, r5, lr}")
    a("")
    a("    /// Initialize mask = 0")
    a("    movs    r0, #0              @ error_mask = 0")
    a("    movs    r4, #0              @ constraint index = 0")
    a(f"    movs    r5, #{n}             @ total constraints")
    a("")
    a("    /// NaN check: compare val with itself")
    a("    vcmp.f32    s0, s0")
    a("    vmrs    APSR_nzcv, fpscr")
    a("    beq     .L_not_nan")
    a(f"    mvn     r0, #(0xFF >> {8 - n})  @ NaN → all bits set")
    a("    b       .L_done")
    a("")
    a(".L_not_nan:")
    a("    /// Load bounds table address")
    a("    ldr     r1, =bounds_lo")
    a("    ldr     r2, =bounds_hi")
    a("")
    a(".L_check_loop:")
    a("    cmp     r4, r5")
    a("    bge     .L_done")
    a("")
    a("    /// Load lo[i] and hi[i]")
    a("    adds    r3, r1, r4, lsl #2  @ &bounds_lo[i]")
    a("    vldr.32 s1, [r3]            @ s1 = lo[i]")
    a("    adds    r3, r2, r4, lsl #2  @ &bounds_hi[i]")
    a("    vldr.32 s2, [r3]            @ s2 = hi[i]")
    a("")
    a("    /// Check val < lo[i]")
    a("    vcmp.f32    s0, s1")
    a("    vmrs    APSR_nzcv, fpscr")
    a("    bmi     .L_violate           @ val < lo → violate")
    a("")
    a("    /// Check val > hi[i]")
    a("    vcmp.f32    s0, s2")
    a("    vmrs    APSR_nzcv, fpscr")
    a("    bgt     .L_violate           @ val > hi → violate")
    a("")
    a("    b       .L_next")
    a("")
    a(".L_violate:")
    a("    /// Set bit i in error_mask")
    a("    movs    r3, #1")
    a("    lsls    r3, r4              @ r3 = 1 << i")
    a("    orrs    r0, r3              @ mask |= (1 << i)")
    a("")
    a(".L_next:")
    a("    adds    r4, #1              @ i++")
    a("    b       .L_check_loop")
    a("")
    a(".L_done:")
    a("    /// r0 = error_mask, return")
    a("    pop     {r4, r5, pc}")
    a("")
    a("")

    # ── Batch check ─────────────────────────────────────────
    a("    .global flux_check_batch")
    a("    .thumb_func")
    a("")
    a("    /// flux_check_batch(float* values, int count, uint8_t* masks)")
    a("    /// r0 = values ptr, r1 = count, r2 = masks ptr")
    a("flux_check_batch:")
    a("    push    {r4, r5, r6, lr}")
    a("    mov     r4, r0              @ r4 = values")
    a("    mov     r5, r1              @ r5 = count")
    a("    mov     r6, r2              @ r6 = masks")
    a("    movs    r3, #0              @ i = 0")
    a("")
    a(".L_batch_loop:")
    a("    cmp     r3, r5")
    a("    bge     .L_batch_done")
    a("")
    a("    /// Load value[i] into s0")
    a("    adds    r0, r4, r3, lsl #2")
    a("    vldr.32 s0, [r0]")
    a("")
    a("    /// Call check (tail-call friendly inline)")
    a("    push    {r3, r6}           @ save i and masks ptr")
    a("    bl      flux_check_exact")
    a("    pop     {r3, r6}")
    a("")
    a("    /// Store result mask[i] = r0")
    a("    strb    r0, [r6, r3]")
    a("")
    a("    adds    r3, #1")
    a("    b       .L_batch_loop")
    a("")
    a(".L_batch_done:")
    a("    pop     {r4, r5, r6, pc}")
    a("")

    s_path = output_path if output_path.suffix == ".s" else output_path.with_suffix(".s")
    s_path.write_text("\n".join(lines), encoding="utf-8")
    return s_path


def _arm_float(v: float) -> str:
    if math.isinf(v):
        return "1.0e38" if v > 0 else "-1.0e38"  # Approximate for ARM float
    return repr(v)


# ---------------------------------------------------------------------------
# 5. deploy() — master function
# ---------------------------------------------------------------------------

_TARGETS = {
    "c": ("C (gcc)", compile_to_c),
    "wasm": ("WebAssembly", compile_to_wasm),
    "verilog": ("Verilog (FPGA)", compile_to_verilog),
    "arm": ("ARM Cortex-M4", compile_to_asm_arm),
}

ALL_TARGETS = list(_TARGETS.keys())


def deploy(
    target: str,
    constraints: Constraints,
    output_dir: Union[str, Path],
) -> Dict[str, Any]:
    """
    Master deployment function.

    Args:
        target: One of 'c', 'wasm', 'verilog', 'arm', or 'all'
        constraints: List of constraint dicts with lo, hi, name
        output_dir: Directory for output files

    Returns:
        Dict with deployment results per target.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    targets = ALL_TARGETS if target == "all" else [target]
    results: Dict[str, Any] = {}

    for t in targets:
        if t not in _TARGETS:
            results[t] = {"status": "error", "message": f"Unknown target: {t}"}
            continue

        label, compiler = _TARGETS[t]
        t0 = time.time()

        try:
            # Determine output path
            ext_map = {"c": ".c", "wasm": ".wasm", "verilog": ".v", "arm": ".s"}
            out_path = output_dir / f"flux_check{ext_map[t]}"

            # Compile
            generated = compiler(constraints, out_path)
            elapsed = time.time() - t0

            result: Dict[str, Any] = {
                "status": "ok",
                "target": t,
                "label": label,
                "output": str(generated),
                "size_bytes": generated.stat().st_size,
                "compile_time_ms": round(elapsed * 1000, 1),
            }

            # Try to actually compile if tools available
            if t == "c":
                result.update(_try_compile_c(generated, output_dir))
            elif t == "wasm" and generated.suffix == ".wasm":
                result["wasm_compiled"] = True
                result["wasm_size"] = generated.stat().st_size

            results[t] = result

        except Exception as e:
            results[t] = {
                "status": "error",
                "target": t,
                "message": str(e),
                "compile_time_ms": round((time.time() - t0) * 1000, 1),
            }

    # Write README
    _write_readme(constraints, output_dir, results, targets)

    return results


def _try_compile_c(c_path: Path, output_dir: Path) -> Dict[str, Any]:
    """Try to compile generated C with gcc and run it."""
    result: Dict[str, Any] = {}
    binary = output_dir / "flux_check"

    # Try gcc
    try:
        comp = subprocess.run(
            ["gcc", "-O3", "-mavx2", "-lm", "-o", str(binary), str(c_path)],
            capture_output=True, text=True, timeout=30,
        )
        if comp.returncode == 0:
            result["gcc_compiled"] = True
            result["binary_size"] = binary.stat().st_size

            # Try running
            try:
                run = subprocess.run(
                    [str(binary)],
                    capture_output=True, text=True, timeout=10,
                )
                result["run_exit_code"] = run.returncode
                result["run_output"] = run.stdout[:2000]
                if run.returncode == 0:
                    result["passed"] = True
                else:
                    result["passed"] = False
            except Exception as e:
                result["run_error"] = str(e)
        else:
            result["gcc_compiled"] = False
            result["gcc_errors"] = comp.stderr[:1000]
    except FileNotFoundError:
        result["gcc_available"] = False
    except subprocess.TimeoutExpired:
        result["gcc_timeout"] = True

    return result


def _write_readme(
    constraints: Constraints,
    output_dir: Path,
    results: Dict[str, Any],
    targets: List[str],
) -> None:
    """Write a deployment README."""
    n = len(constraints)
    names = [c.get("name", f"C{i}") for i, c in enumerate(constraints)]

    lines: List[str] = []
    a = lines.append

    a("# FLUX Constraint Engine — Deployment Package")
    a("")
    a(f"**Constraints:** {n}")
    a("")
    a("| # | Name | Lower Bound | Upper Bound |")
    a("|---|------|-------------|-------------|")
    for i, nm in enumerate(names):
        a(f"| {i} | {nm} | {constraints[i]['lo']} | {constraints[i]['hi']} |")
    a("")

    a("## Targets")
    a("")
    for t in targets:
        r = results.get(t, {})
        status = r.get("status", "unknown")
        label = _TARGETS.get(t, (t,))[0]
        a(f"### {label}")
        a(f"- Status: {status}")
        if "output" in r:
            a(f"- Output: `{r['output']}`")
        if "size_bytes" in r:
            a(f"- Size: {r['size_bytes']} bytes")
        if "compile_time_ms" in r:
            a(f"- Compile time: {r['compile_time_ms']}ms")
        if r.get("gcc_compiled"):
            a(f"- GCC compiled: ✓")
            if "binary_size" in r:
                a(f"- Binary size: {r['binary_size']} bytes")
            if r.get("passed"):
                a(f"- Tests: **PASSED** ✓")
            elif "run_output" in r:
                a(f"- Tests: see output below")
        if r.get("wasm_compiled"):
            a(f"- WASM binary: ✓ ({r.get('wasm_size', '?')} bytes)")
        if "message" in r:
            a(f"- Error: {r['message']}")
        a("")

    a("## Deployment Instructions")
    a("")
    a("### C (gcc)")
    a("```bash")
    a("gcc -O3 -mavx2 -lm -o flux_check flux_check.c")
    a("./flux_check")
    a("```")
    a("")
    a("### WebAssembly")
    a("```bash")
    a("wat2wasm flux_check.wat -o flux_check.wasm")
    a("```")
    a("")
    a("### Verilog (FPGA)")
    a("```bash")
    a("iverilog -o flux_check.vvp flux_check.v")
    a("vvp flux_check.vvp")
    a("```")
    a("")
    a("### ARM Cortex-M4")
    a("```bash")
    a("arm-none-eabi-as -mcpu=cortex-m4 -mthumb -o flux_check.o flux_check.s")
    a("arm-none-eabi-ld -o flux_check.elf flux_check.o")
    a("```")
    a("")
    a("---")
    a("*Generated by flux_deploy.py — FLUX v4 Deployment Pipeline*")

    (output_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")
