"""
flux_category.py — Category-theoretic foundations for constraint systems.

Implements:
- ConstraintFunctor: functor from constraint sets to Boolean algebras
- ConstraintMonad: the Checked monad (and comonad) for constraint checking
- ConstraintSheaf: sheaf of constraint results with gluing and cohomology
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import (
    Any,
    Callable,
    Generic,
    TypeVar,
    Hashable,
)

T = TypeVar("T")
U = TypeVar("U")


# ═══════════════════════════════════════════════════════════
#  Boolean Algebra of Definable Subsets
# ═══════════════════════════════════════════════════════════

class BooleanAlgebra:
    """Finite Boolean algebra represented as a collection of subsets of a carrier set."""

    def __init__(self, carrier: frozenset, definable: frozenset[frozenset]):
        """
        Args:
            carrier: the underlying set (as frozenset)
            definable: collection of definable subsets (each a frozenset)
        """
        self.carrier = carrier
        self._definable = definable
        # Verify closure under Boolean operations
        self._verify_axioms()

    def _verify_axioms(self) -> None:
        # Must contain bottom and top
        assert frozenset() in self._definable, "Must contain empty set"
        assert self.carrier in self._definable, "Must contain carrier"
        # Closed under complement
        for s in self._definable:
            comp = self.carrier - s
            assert comp in self._definable, f"Not closed under complement: {comp}"
        # Closed under pairwise union and intersection
        elements = list(self._definable)
        for i, a in enumerate(elements):
            for b in elements[i + 1:]:
                assert (a | b) in self._definable, f"Not closed under union: {a | b}"
                assert (a & b) in self._definable, f"Not closed under intersection: {a & b}"

    @property
    def elements(self) -> frozenset[frozenset]:
        return self._definable

    def complement(self, s: frozenset) -> frozenset:
        assert s in self._definable
        return self.carrier - s

    def union(self, a: frozenset, b: frozenset) -> frozenset:
        assert a in self._definable and b in self._definable
        return a | b

    def intersection(self, a: frozenset, b: frozenset) -> frozenset:
        assert a in self._definable and b in self._definable
        return a & b

    def top(self) -> frozenset:
        return self.carrier

    def bottom(self) -> frozenset:
        return frozenset()

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, BooleanAlgebra):
            return NotImplemented
        return self.carrier == other.carrier and self._definable == other._definable

    def __hash__(self) -> int:
        return hash((self.carrier, self._definable))

    def __repr__(self) -> str:
        return f"BA(carrier={set(self.carrier)}, |{len(self._definable)} elements)"


# ═══════════════════════════════════════════════════════════
#  Constraint Set and the Definable-Subset Functor
# ═══════════════════════════════════════════════════════════

@dataclass(frozen=True)
class ConstraintSet:
    """A constraint set: a carrier set plus a collection of constraint predicates."""

    carrier: frozenset
    # Each constraint is a frozenset (the satisfying subset)
    constraints: frozenset[frozenset] = field(default_factory=frozenset)

    def is_separated(self) -> bool:
        """Check if definable subsets separate all points."""
        ba = self.boolean_algebra()
        for x in self.carrier:
            for y in self.carrier:
                if x != y:
                    # Find a definable set containing x but not y
                    found = False
                    for s in ba.elements:
                        if x in s and y not in s:
                            found = True
                            break
                    if not found:
                        return False
        return True

    def boolean_algebra(self) -> BooleanAlgebra:
        """Compute the Boolean algebra of definable subsets.

        Generated by closing the constraint subsets under complement,
        union, and intersection.
        """
        if not self.carrier:
            return BooleanAlgebra(
                frozenset(),
                frozenset({frozenset()})
            )

        # Start with given constraints + empty + carrier
        current: set[frozenset] = {frozenset(), self.carrier}
        current.update(self.constraints)

        # Close under Boolean operations (iterate to fixed point)
        changed = True
        while changed:
            changed = False
            to_add: set[frozenset] = set()
            elements = list(current)
            for s in elements:
                comp = self.carrier - s
                if comp not in current:
                    to_add.add(comp)
            for i, a in enumerate(elements):
                for b in elements[i + 1:]:
                    u = a | b
                    inter = a & b
                    if u not in current:
                        to_add.add(u)
                    if inter not in current:
                        to_add.add(inter)
            if to_add:
                current.update(to_add)
                changed = True

        return BooleanAlgebra(self.carrier, frozenset(current))


@dataclass(frozen=True)
class ConstraintMorphism:
    """A constraint-preserving function between constraint sets."""

    source: ConstraintSet
    target: ConstraintSet
    mapping: dict  # element -> element

    def __post_init__(self) -> None:
        # Verify it's a valid function
        for x in self.source.carrier:
            assert x in self.mapping, f"Missing mapping for {x}"
            assert self.mapping[x] in self.target.carrier, f"Maps outside target"

    def apply(self, element: Any) -> Any:
        return self.mapping[element]

    def preimage(self, subset: frozenset) -> frozenset:
        """f^{-1}(S) for S ⊆ target."""
        return frozenset(x for x in self.source.carrier if self.mapping[x] in subset)

    def is_constraint_preserving(self) -> bool:
        """Check if preimage of every definable subset is definable."""
        target_ba = self.target.boolean_algebra()
        source_ba = self.source.boolean_algebra()
        for s in target_ba.elements:
            pre = self.preimage(s)
            if pre not in source_ba.elements:
                return False
        return True

    def functor_image(self) -> "BAHomomorphism":
        """Compute F(f): the Boolean algebra homomorphism induced by this morphism.

        F is contravariant: F(f): F(target) → F(source) via preimage.
        """
        assert self.is_constraint_preserving(), "Not constraint-preserving"
        target_ba = self.target.boolean_algebra()
        mapping = {}
        for s in target_ba.elements:
            mapping[s] = self.preimage(s)
        return BAHomomorphism(
            source=target_ba,
            target=target_ba,  # just for structural typing
            preimage_map=mapping,
        )


@dataclass(frozen=True)
class BAHomomorphism:
    """A Boolean algebra homomorphism (via preimage)."""
    source: BooleanAlgebra
    target: BooleanAlgebra
    preimage_map: dict[frozenset, frozenset]


# ═══════════════════════════════════════════════════════════
#  The Constraint Monad (Checked)
# ═══════════════════════════════════════════════════════════

class CheckStatus(Enum):
    OK = "ok"
    FAILED = "failed"


@dataclass(frozen=True)
class Checked(Generic[T]):
    """The constraint-checking monad: Checked[T] is either Ok(value) or Failed(error)."""

    status: CheckStatus
    value: T | None = None
    error: str | None = None

    @staticmethod
    def ok(value: T) -> "Checked[T]":
        return Checked(status=CheckStatus.OK, value=value)

    @staticmethod
    def failed(error: str) -> "Checked[T]":
        return Checked(status=CheckStatus.FAILED, error=error)

    # ── Monad operations ──

    @staticmethod
    def ret(value: T) -> "Checked[T]":
        """return :: a -> Checked a  (trivial always-true constraint)"""
        return Checked.ok(value)

    def bind(self, f: Callable[[T], "Checked[U]"]) -> "Checked[U]":
        """bind :: Checked a -> (a -> Checked b) -> Checked b"""
        if self.status == CheckStatus.FAILED:
            return Checked.failed(self.error)  # type: ignore
        return f(self.value)  # type: ignore

    def __rshift__(self, f: Callable[[T], "Checked[U]"]) -> "Checked[U]":
        """Operator >>= for convenient chaining."""
        return self.bind(f)

    # ── Comonad operations ──

    def extract(self) -> T:
        """extract :: Checked a -> a (fails on invalid)"""
        if self.status == CheckStatus.FAILED:
            raise ValueError(f"Cannot extract from Failed: {self.error}")
        return self.value  # type: ignore

    def duplicate(self) -> "Checked[Checked[T]]":
        """duplicate :: Checked a -> Checked (Checked a)"""
        if self.status == CheckStatus.FAILED:
            return Checked.failed(self.error)  # type: ignore
        return Checked.ok(Checked.ok(self.value))  # type: ignore

    # ── Functor ──

    def fmap(self, f: Callable[[T], U]) -> "Checked[U]":
        """fmap :: (a -> b) -> Checked a -> Checked b"""
        if self.status == CheckStatus.FAILED:
            return Checked.failed(self.error)  # type: ignore
        return Checked.ok(f(self.value))  # type: ignore

    def __repr__(self) -> str:
        if self.status == CheckStatus.OK:
            return f"Ok({self.value!r})"
        return f"Failed({self.error!r})"


# ═══════════════════════════════════════════════════════════
#  Constraint Sheaf
# ═══════════════════════════════════════════════════════════

@dataclass(frozen=True)
class OpenSet:
    """An open set in a topological space, represented as a frozenset of points."""

    points: frozenset

    def __contains__(self, point: Any) -> bool:
        return point in self.points

    def intersect(self, other: "OpenSet") -> "OpenSet":
        return OpenSet(self.points & other.points)

    def union_with(self, other: "OpenSet") -> "OpenSet":
        return OpenSet(self.points | other.points)

    def is_subset_of(self, other: "OpenSet") -> bool:
        return self.points.issubset(other.points)


@dataclass
class Section:
    """A section of the constraint sheaf over an open set: local constraint result."""

    domain: OpenSet
    data: dict  # point -> constraint result (bool)

    def restrict(self, subdomain: OpenSet) -> "Section":
        """Restrict section to a smaller open set."""
        assert subdomain.is_subset_of(self.domain)
        return Section(
            domain=subdomain,
            data={p: v for p, v in self.data.items() if p in subdomain.points}
        )

    def agrees_with(self, other: "Section", overlap: OpenSet) -> bool:
        """Check if two sections agree on their overlap."""
        for p in overlap.points:
            if p in self.data and p in other.data:
                if self.data[p] != other.data[p]:
                    return False
        return True


class ConstraintSheaf:
    """Sheaf of constraint results on a topological space.

    Assigns to each open set U the set of valid constraint results on U,
    with restriction maps for inclusions V ⊆ U.
    """

    def __init__(self) -> None:
        self._sections: dict[frozenset, Section] = {}

    def assign(self, open_set: OpenSet, section: Section) -> None:
        """Assign a section to an open set."""
        assert section.domain.points == open_set.points
        self._sections[open_set.points] = section

    def restrict(self, domain: OpenSet, subdomain: OpenSet) -> Section | None:
        """Restriction map: res_{V,U}: F(U) → F(V)."""
        if domain.points in self._sections:
            return self._sections[domain.points].restrict(subdomain)
        return None

    def glue(self, sections: list[Section], cover: list[OpenSet]) -> Section | None:
        """Try to glue local sections into a global section.

        Returns None if sections don't agree on overlaps (sheaf condition fails).
        """
        if not sections:
            return None

        # Check pairwise agreement on overlaps
        for i in range(len(sections)):
            for j in range(i + 1, len(sections)):
                overlap = cover[i].intersect(cover[j])
                if overlap.points and not sections[i].agrees_with(sections[j], overlap):
                    return None  # Sheaf condition fails

        # Glue: merge data from all sections
        merged_data: dict = {}
        merged_points: set = set()
        for s in sections:
            merged_points.update(s.domain.points)
            for p, v in s.data.items():
                if p in merged_data and merged_data[p] != v:
                    return None  # Conflict
                merged_data[p] = v

        return Section(domain=OpenSet(frozenset(merged_points)), data=merged_data)

    def h1_obstruction(self, cover: list[OpenSet], local_sections: list[Section]) -> dict | None:
        """Compute H^1 obstruction: measure of global constraint conflict.

        Returns the cocycle (disagreements on overlaps) if any, or None if trivial.
        """
        obstructions: dict = {}
        for i in range(len(local_sections)):
            for j in range(i + 1, len(local_sections)):
                overlap = cover[i].intersect(cover[j])
                if overlap.points:
                    for p in overlap.points:
                        if (p in local_sections[i].data and
                                p in local_sections[j].data and
                                local_sections[i].data[p] != local_sections[j].data[p]):
                            key = (i, j, p)
                            obstructions[key] = {
                                "section_i": local_sections[i].data[p],
                                "section_j": local_sections[j].data[p],
                            }
        return obstructions if obstructions else None


# ═══════════════════════════════════════════════════════════
#  Natural Transformations Between Strategies
# ═══════════════════════════════════════════════════════════

class CheckerStrategy(Enum):
    EXACT = "exact"
    PREDICTIVE = "predictive"  # overapproximation
    SAMPLING = "sampling"      # underapproximation


@dataclass
class StrategyFunctor:
    """A constraint-checking strategy as a functor from ConstraintSets to BoolAlg."""

    strategy: CheckerStrategy

    def apply(self, cs: ConstraintSet) -> BooleanAlgebra:
        ba = cs.boolean_algebra()
        if self.strategy == CheckerStrategy.EXACT:
            return ba
        elif self.strategy == CheckerStrategy.PREDICTIVE:
            # Overapproximation: add the full carrier as a definable set
            # and close (for demo, return the full powerset)
            return self._powerset(ba.carrier)
        else:  # SAMPLING
            # Underapproximation: return only {empty, carrier}
            return BooleanAlgebra(
                ba.carrier,
                frozenset({frozenset(), ba.carrier})
            )

    @staticmethod
    def _powerset(carrier: frozenset) -> BooleanAlgebra:
        """Full powerset Boolean algebra."""
        from itertools import chain, combinations
        ps = frozenset(
            frozenset(combo)
            for r in range(len(carrier) + 1)
            for combo in combinations(carrier, r)
        )
        return BooleanAlgebra(carrier, ps)


@dataclass
class NaturalTransformation:
    """A natural transformation between two checker strategies."""

    source_strategy: CheckerStrategy
    target_strategy: CheckerStrategy

    def component(self, cs: ConstraintSet) -> Callable[[frozenset], frozenset]:
        """η_C: F(C) → G(C) for a given constraint set C.

        Returns a function mapping definable subsets in the source to the target.
        """
        source_ba = StrategyFunctor(self.source_strategy).apply(cs)
        target_ba = StrategyFunctor(self.target_strategy).apply(cs)

        if self.source_strategy == CheckerStrategy.SAMPLING and \
                self.target_strategy == CheckerStrategy.EXACT:
            # Inclusion: sampling ⊆ exact
            def eta(s: frozenset) -> frozenset:
                assert s in source_ba.elements
                assert s in target_ba.elements
                return s
            return eta

        elif self.source_strategy == CheckerStrategy.EXACT and \
                self.target_strategy == CheckerStrategy.PREDICTIVE:
            # Inclusion: exact ⊆ predictive
            def eta(s: frozenset) -> frozenset:
                assert s in source_ba.elements
                assert s in target_ba.elements
                return s
            return eta

        else:
            # Generic: identity on common elements
            def eta(s: frozenset) -> frozenset:
                return s
            return eta

    def is_sound(self, cs: ConstraintSet) -> bool:
        """Soundness: η_C(S) ⊆ S for all S — no false positives."""
        source_ba = StrategyFunctor(self.source_strategy).apply(cs)
        eta = self.component(cs)
        for s in source_ba.elements:
            result = eta(s)
            if not result.issubset(s):
                return False
        return True

    def is_complete(self, cs: ConstraintSet) -> bool:
        """Completeness: S ⊆ η_C(S) for all S — no false negatives."""
        source_ba = StrategyFunctor(self.source_strategy).apply(cs)
        eta = self.component(cs)
        for s in source_ba.elements:
            result = eta(s)
            if not s.issubset(result):
                return False
        return True
